// src/data.js
import {
  FaUser,
  FaIdBadge,
  FaBirthdayCake,
  FaPhone,
  FaEnvelope,
  FaCalendarAlt,
  FaBriefcase,
  FaBuilding,
} from "react-icons/fa";
import { FaLaptopCode, FaAddressCard } from "react-icons/fa";
import { MdOutlinePhoneAndroid } from "react-icons/md";
import { IoMdTabletLandscape } from "react-icons/io";
import adilbhai from "../../../Images/adilbhai.jpg";
import asadbhai from "../../../Images/asadbhai.jpg";
import salman from "../../../Images/salman.jpg";
import arslaan from "../../../Images/arslaan.jpg";

export const users = [
  {
    name: "Shereyar SM Adil",
    id: 1,
    country: "India",
    joiningDate: "2020-05-15",
    jobTitle: "Software Engineer",
    role: "Manager",
    image: adilbhai,
    bgColor: "bg-yellow-100",
    employmentType: "Full-time",
    details: "Details",
    manager: "Jane Smith",
    dob: "1990-01-01",
    phone: "+1-234-567-8900",
    email: "john.doe@example.com",
    salary: "$100,000",
    allowance: "$5,000",
    hra: "200",
    ta: "400",
    leave: "3",
    pf: "300",
    department: "IT",
    equipments: [
      {
        item: "Laptop",
        icon: <FaLaptopCode size={32} />,
        issue: "Issue Date",
        date: "31/02/2024",
      },
      {
        item: "Mobile",
        icon: <MdOutlinePhoneAndroid size={32} />,
        issue: "Issue Date",
        date: "31/02/2024",
      },
    ],
    basicInfo: [
      {
        label: "Name",
        value: "Shereyar SM Adil",
        icon: <FaUser size={24} className="m-auto" />,
      },
      {
        label: "Employee ID",
        value: "01",
        icon: <FaIdBadge size={24} className="m-auto" />,
      },
      {
        label: "Date of Birth",
        value: "1990-01-01",
        icon: <FaBirthdayCake size={24} className="m-auto" />,
      },
      {
        label: "Phone",
        value: "+1-234-567-8900",
        icon: <FaPhone size={24} className="m-auto" />,
      },
      {
        label: "Email",
        value: "john.doe@example.com",
        icon: <FaEnvelope size={24} className="m-auto" />,
      },
    ],
    employmentInfo: [
      {
        label: "Date of Joining",
        value: "2020-05-15",
        icon: <FaCalendarAlt size={24} className="m-auto" />,
      },
      {
        label: "Job Title",
        value: "Software Engineer",
        icon: <FaBriefcase size={24} className="m-auto" />,
      },
      {
        label: "Department",
        value: "Engineering",
        icon: <FaBuilding size={24} className="m-auto" />,
      },
      {
        label: "Reporting Manager",
        value: "Jane Smith",
        icon: <FaUser size={24} className="m-auto" />,
      },
      {
        label: "Employment Type",
        value: "Full-time",
        icon: <FaBriefcase size={24} className="m-auto" />,
      },
    ],
  },
  {
    name: "Asad Khan",
    id: 2,
    country: "India",
    joiningDate: "2020-05-15",
    jobTitle: "Software Engineer",
    role: "Manager",
    image: asadbhai,
    bgColor: "bg-yellow-100",
    employmentType: "Full-time",
    details: "Details",
    manager: "Jane Smith",
    dob: "1990-01-01",
    phone: "+1-234-567-8900",
    email: "john.doe@example.com",
    salary: "$100,000",
    allowance: "$5,000",
    hra: "200",
    ta: "400",
    pf: "300",
    leave: "3",
    department: "HR",
    equipments: [
      {
        item: "Laptop",
        icon: <FaLaptopCode size={32} />,
        issue: "Issue Date",
        date: "31/02/2024",
      },
      {
        item: "Mobile",
        icon: <MdOutlinePhoneAndroid size={32} />,
        issue: "Issue Date",
        date: "31/02/2024",
      },
    ],
    basicInfo: [
      {
        label: "Name",
        value: "Asad Khan",
        icon: <FaUser size={24} className="m-auto" />,
      },
      {
        label: "Employee ID",
        value: "12",
        icon: <FaIdBadge size={24} className="m-auto" />,
      },
      {
        label: "Date of Birth",
        value: "1990-01-01",
        icon: <FaBirthdayCake size={24} className="m-auto" />,
      },
      {
        label: "Phone",
        value: "+1-234-567-8900",
        icon: <FaPhone size={24} className="m-auto" />,
      },
      {
        label: "Email",
        value: "john.doe@example.com",
        icon: <FaEnvelope size={24} className="m-auto" />,
      },
    ],
    employmentInfo: [
      {
        label: "Date of Joining",
        value: "2020-05-15",
        icon: <FaCalendarAlt size={24} className="m-auto" />,
      },
      {
        label: "Job Title",
        value: "Software Engineer",
        icon: <FaBriefcase size={24} className="m-auto" />,
      },
      {
        label: "Department",
        value: "Engineering",
        icon: <FaBuilding size={24} className="m-auto" />,
      },
      {
        label: "Reporting Manager",
        value: "Jane Smith",
        icon: <FaUser size={24} className="m-auto" />,
      },
      {
        label: "Employment Type",
        value: "Full-time",
        icon: <FaBriefcase size={24} className="m-auto" />,
      },
    ],
  },
  {
    name: "Salman Akhtar",
    id: 3,
    country: "India",
    joiningDate: "2020-05-15",
    jobTitle: "Software Engineer",
    role: "Manager",
    image: salman,
    bgColor: "bg-yellow-100",
    employmentType: "Full-time",
    details: "Details",
    manager: "Jane Smith",
    dob: "1990-01-01",
    phone: "+1-234-567-8900",
    email: "john.doe@example.com",
    salary: "$100,000",
    allowance: "$5,000",
    hra: "200",
    ta: "400",
    pf: "300",
    leave: "3",
    department: "HR",
    equipments: [
      {
        item: "Laptop",
        icon: <FaLaptopCode size={32} />,
        issue: "Issue Date",
        date: "31/02/2024",
      },
      {
        item: "Mobile",
        icon: <MdOutlinePhoneAndroid size={32} />,
        issue: "Issue Date",
        date: "31/02/2024",
      },
    ],
    basicInfo: [
      {
        label: "Name",
        value: "Salman Akhtar",
        icon: <FaUser size={24} className="m-auto" />,
      },
      {
        label: "Employee ID",
        value: "02",
        icon: <FaIdBadge size={24} className="m-auto" />,
      },
      {
        label: "Date of Birth",
        value: "1990-01-01",
        icon: <FaBirthdayCake size={24} className="m-auto" />,
      },
      {
        label: "Phone",
        value: "+1-234-567-8900",
        icon: <FaPhone size={24} className="m-auto" />,
      },
      {
        label: "Email",
        value: "john.doe@example.com",
        icon: <FaEnvelope size={24} className="m-auto" />,
      },
    ],
    employmentInfo: [
      {
        label: "Date of Joining",
        value: "2020-05-15",
        icon: <FaCalendarAlt size={24} className="m-auto" />,
      },
      {
        label: "Job Title",
        value: "Software Engineer",
        icon: <FaBriefcase size={24} className="m-auto" />,
      },
      {
        label: "Department",
        value: "Engineering",
        icon: <FaBuilding size={24} className="m-auto" />,
      },
      {
        label: "Reporting Manager",
        value: "Jane Smith",
        icon: <FaUser size={24} className="m-auto" />,
      },
      {
        label: "Employment Type",
        value: "Full-time",
        icon: <FaBriefcase size={24} className="m-auto" />,
      },
    ],
  },
  {
    name: "Arslaan Ahmad",
    id: 4,
    country: "Iqra Colony",
    joiningDate: "2022-01-10",
    jobTitle: "Web Developer",
    role: "Developer",
    image: arslaan,
    bgColor: "bg-slate-100",
    employmentType: "Full-time",
    details: "Details",
    manager: "Jane Smith",
    dob: "1992-03-15",
    phone: "+1-234-567-8901",
    email: "arslaan.ahmad@example.com",
    salary: "$100,000",
    allowance: "$5,000",
    hra: "200",
    ta: "400",
    pf: "300",
    leave: "3",
    department: "Sales",
    equipments: [
      {
        item: "Laptop",
        icon: <FaLaptopCode size={32} />,
        issue: "Issue Date",
        date: "31/02/2024",
      },
    ],
    basicInfo: [
      {
        label: "Name",
        value: "Arslaan Ahmad",
        icon: <FaUser size={24} className="m-auto" />,
      },
      {
        label: "Employee ID",
        value: "04",
        icon: <FaIdBadge size={24} className="m-auto" />,
      },
      {
        label: "Date of Birth",
        value: "1992-03-15",
        icon: <FaBirthdayCake size={24} className="m-auto" />,
      },
      {
        label: "Phone",
        value: "+1-234-567-8901",
        icon: <FaPhone size={24} className="m-auto" />,
      },
      {
        label: "Email",
        value: "arslaan.ahmad@example.com",
        icon: <FaEnvelope size={24} className="m-auto" />,
      },
    ],
    employmentInfo: [
      {
        label: "Date of Joining",
        value: "2022-01-10",
        icon: <FaCalendarAlt size={24} className="m-auto" />,
      },
      {
        label: "Job Title",
        value: "Web Developer",
        icon: <FaBriefcase size={24} className="m-auto" />,
      },
      {
        label: "Department",
        value: "Development",
        icon: <FaBuilding size={24} className="m-auto" />,
      },
      {
        label: "Reporting Manager",
        value: "Jane Smith",
        icon: <FaUser size={24} className="m-auto" />,
      },
      {
        label: "Employment Type",
        value: "Full-time",
        icon: <FaBriefcase size={24} className="m-auto" />,
      },
    ],
  },
  {
    name: "Ayaan Khan",
    id: 5,
    country: "Pakistan",
    joiningDate: "2021-02-20",
    jobTitle: "Data Analyst",
    role: "Analyst",
    image: salman,
    bgColor: "bg-blue-100",
    employmentType: "Part-time",
    details: "Details",
    manager: "John Doe",
    dob: "1988-05-10",
    phone: "+92-345-678-9012",
    email: "ayaan.khan@example.com",
    salary: "$50,000",
    allowance: "$2,500",
    hra: "100",
    ta: "200",
    pf: "150",
    leave: "5",
    department: "IT",
    equipments: [
      {
        item: "Tablet",
        icon: <IoMdTabletLandscape size={32} />,
        issue: "Issue Date",
        date: "01/03/2023",
      },
    ],
    basicInfo: [
      {
        label: "Name",
        value: "Ayaan Khan",
        icon: <FaUser size={24} className="m-auto" />,
      },
      {
        label: "Employee ID",
        value: "05",
        icon: <FaIdBadge size={24} className="m-auto" />,
      },
      {
        label: "Date of Birth",
        value: "1988-05-10",
        icon: <FaBirthdayCake size={24} className="m-auto" />,
      },
      {
        label: "Phone",
        value: "+92-345-678-9012",
        icon: <FaPhone size={24} className="m-auto" />,
      },
      {
        label: "Email",
        value: "ayaan.khan@example.com",
        icon: <FaEnvelope size={24} className="m-auto" />,
      },
    ],
    employmentInfo: [
      {
        label: "Date of Joining",
        value: "2021-02-20",
        icon: <FaCalendarAlt size={24} className="m-auto" />,
      },
      {
        label: "Job Title",
        value: "Data Analyst",
        icon: <FaBriefcase size={24} className="m-auto" />,
      },
      {
        label: "Department",
        value: "Analytics",
        icon: <FaBuilding size={24} className="m-auto" />,
      },
      {
        label: "Reporting Manager",
        value: "John Doe",
        icon: <FaUser size={24} className="m-auto" />,
      },
      {
        label: "Employment Type",
        value: "Part-time",
        icon: <FaBriefcase size={24} className="m-auto" />,
      },
    ],
  },
];
